apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-helm-app.fullname" . }}
  labels:
    app: {{ include "my-helm-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-helm-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-helm-app.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-helm-app.fullname" . }}-config
                  key: welcomeMessage
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-helm-app.fullname" . }}-secret
                  key: password
